# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Eworkplace' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Eworkplace

  target 'EworkplaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Eworkplace-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Eworkplace-tvOS

  target 'Eworkplace-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
